### ISSUE TITLE
Location Picker Crashes on  android 6.0 MarshMallow

### ISSUE THREAD

**Issue by RotBolt** [Dvik/Taskzy#6]
Place Picker doesn't work on android 6.0 marshmallow

**Comment by Dvik** [comment]
Tested it on Android 6.0 and the Place Picker works fine.

**Comment by RotBolt** [comment]
Here read this 
https://issuetracker.google.com/issues/35829218
There are some devices on which place picker doesn't work 
Including Xiaomi Redmi Note 4   6.0.1 marshmallow
And some other
